name: Build Release

on:
  release:
    types: [published]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: arc-runner-set
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, linux/arm64, darwin/amd64, darwin/arm64
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1.40
      with:
        github_token: ${{ secrets.ETH_SYNC_CHECK_GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: sync-check
        asset_name: sync-check-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
        project_path: ./cmd/sync-check
